using WebApi.Models.Database.Learner;

namespace WebApi.Initializers.LearnerInitializers;

public class LanguagesInitializer
{
    public static IEnumerable<Language> GetSomeLanguages()
        => languages.Distinct().Select(l => new Language() { Name = l });

    static string[] languages = {
        "English",
        "Spanish",
        "French",
        "German",
        "Italian",
        "Portuguese",
        "Russian",
        "Chinese",
        "Japanese",
        "Korean",
        "Arabic",
        "Hindi",
        "Bengali",
        "Punjabi",
        "Urdu",
        "Turkish",
        "Dutch",
        "Swedish",
        "Norwegian",
        "Danish",
        "Finnish",
        "Greek",
        "Polish",
        "Czech",
        "Hungarian",
        "Romanian",
        "Thai",
        "Indonesian",
        "Vietnamese",
        "Hebrew",
        "Swahili",
        "Kiswahili",
        "Tagalog",
        "Malay",
        "Kazakh",
        "Ukrainian",
        "Bulgarian",
        "Slovak",
        "Slovenian",
        "Croatian",
        "Serbian",
        "Macedonian",
        "Albanian",
        "Estonian",
        "Latvian",
        "Lithuanian",
        "Icelandic",
        "Maltese",
        "Farsi",
        "Persian",
        "Sinhala",
        "Tamil",
        "Telugu",
        "Kannada",
        "Marathi",
        "Gujarati",
        "Odia",
        "Afrikaans",
        "Zulu",
        "Xhosa",
        "Sotho",
        "Tswana",
        "Swazi",
        "Ndebele",
        "Sesotho",
        "Tsonga"
    };
}